/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WindowsIO */

#ifndef _Included_WindowsIO
#define _Included_WindowsIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WindowsIO
 * Method:    keyPress
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_WindowsIO_keyPress
  (JNIEnv *, jobject, jchar);

/*
 * Class:     WindowsIO
 * Method:    keyRelease
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_WindowsIO_keyRelease
  (JNIEnv *, jobject, jchar);

/*
 * Class:     WindowsIO
 * Method:    typeChar
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_WindowsIO_typeChar
  (JNIEnv *, jobject, jchar);

/*
 * Class:     WindowsIO
 * Method:    typeString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_WindowsIO_typeString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     WindowsIO
 * Method:    mousePress
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_WindowsIO_mousePress
  (JNIEnv *, jobject, jchar);

/*
 * Class:     WindowsIO
 * Method:    mouseRelease
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_WindowsIO_mouseRelease
  (JNIEnv *, jobject, jchar);

/*
 * Class:     WindowsIO
 * Method:    mouseScroll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_WindowsIO_mouseScroll
  (JNIEnv *, jobject, jint);

/*
 * Class:     WindowsIO
 * Method:    getMouseX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_WindowsIO_getMouseX
  (JNIEnv *, jobject);

/*
 * Class:     WindowsIO
 * Method:    getMouseY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_WindowsIO_getMouseY
  (JNIEnv *, jobject);

/*
 * Class:     WindowsIO
 * Method:    mouseMoveRelative
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_WindowsIO_mouseMoveRelative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     WindowsIO
 * Method:    mouseMoveAbsolute
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_WindowsIO_mouseMoveAbsolute
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     WindowsIO
 * Method:    mouseMoveAbsoluteVirtual
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_WindowsIO_mouseMoveAbsoluteVirtual
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     WindowsIO
 * Method:    getPixel
 * Signature: (II)Ljava/awt/Color;
 */
JNIEXPORT jobject JNICALL Java_WindowsIO_getPixel
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     WindowsIO
 * Method:    getClipboardText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_WindowsIO_getClipboardText
  (JNIEnv *, jobject);

/*
 * Class:     WindowsIO
 * Method:    setClipboardText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_WindowsIO_setClipboardText
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
